swagger: "2.0"

info:
  version: 1.0.0
  title: DSME Smart Manual Server API
  description: Manual Management API Specification

schemes:
  - http
#host: localhost:3300
basePath: /

tags: 
  name: Directory
    description: Directory Scan

  name: Download
    description: Download pdf file

paths:
  /api/directory:
    get:
      summary: return directoy structure in JSON format
      tags: [Directory]
      description: Provide directory structure information and .pdf file path information.
      responses:
        200:
          description: Successful operation
          content: application/json
          schema:
            type: object
            properties: 
              PdfTotalCount:
                type: integer
              DirectoryTree:
                type: object
                properties:
                  path: string
                  name: string
                  children: array
        404:
          description: Directory not found

              


  /api/download:
    get:
      summary: Download .pdf file
      tags: [Download]
      description: Provide .pdf file by path information. Ex) path = A/engineA/engineA.pdf
      parameters:
        - name: path
          in: query
          required: true
          type: string
          description: The file path for download
      responses:
        200:
          description: Successful operation
          content: application/pdf
          schema:
            type: object
            properties: 
              Download file:
                type: object
        400: 
          description: Invalid path supplied
        404:
          description: File not found
            
